# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-171740171-1'

menu:
- {name: 'Playing', folder: 'pages', file: 'playing.html'}
- {name: 'About', folder: 'pages', file: 'ttmb.html'}
- {name: 'Contribute', folder: 'pages', file: 'contribute.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'twitter', link: 'https://twitter.com/tribesthatmaybe'}
- {icon: 'facebook', link: 'https://www.facebook.com/tribesthatmaybe'}
#- {icon: 'instagram', link: 'https://instagram.com/paululele'}
- {icon: 'envelope', link: 'mailto:info@tribesthatmay.be'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Published on'

site:
  title: "Tribes That May Be"
  description: "lo-fi zone trips"
  author: "ttmb crew"
